### ISSUE TITLE
Couldnt find sound player

### ISSUE THREAD

**Issue by pumpingdad** [jef/streetmerchant#1116]
Hey Jef,

I restarted streetmerchant, and suddenly it says: Couldnt find sound player.

I have .env like this: PLAY_SOUND="C:\streetmerchant\alert.wav"

It used to work. What is wrong?

**Comment by wcoleman320** [comment]
I have the same issue

**Comment by jef84142** [comment]
I had the same issue. I was able to fix it by just using the relative path. Since it is already in the Streetmerchant directory you can set it to just "alert.wav". This may not be the issue, but it is what worked for me.

**Comment by wcoleman320** [comment]
My path was wrong, I still get the same error. I double-checked everything. The location on the sound is C:\streetmerchant. In the .env i have it set to PLAY_SOUND="alert.wav". Changed the sound name to alert. I have used MP3 and WAV files.

**Comment by pumpingdad** [comment]
double-checked it, also tried relative path, not working. Renamed file not working, created new folder tried relative path with is sounds\alert.wav , not working :-( Will try to redownload a new sound file and test it.

**Comment by pumpingdad** [comment]
Also downloaded a new file not working :-(

**Comment by soalireofastora20** [comment]
I found a fix for this.

So this is most likely because you're using streetmerchant on Windows and Windows does not have an in-built command-line audio file player. To get around this you can follow these steps:

1.  Download the cmdmp3 binaries form the blogpost in this GitHub repository: https://github.com/jimlawless/cmdmp3
(This is a command-line mp3 player that is supported by the "play-sound" module streetmerchant uses to play sounds you specify)
2. Extract the zip and place the executables in a folder of your choosing.
2a. You should be setting the executables to only have read & execute privileges for all users that aren't administrators of the PC. This is because we're about to add the executables to your "path" environment variable and this can make your system vulnerable to privilege escalation vulnerabilities if the exectuables aren't provisioned the correct access.
3. Hit the windows key and type in "environment variables", you should be able to access a "Edit the system environment variables" window. In the bottom right, hit environment variables and then in the new window, "Path" and edit (for your user).
3a. Click "New" and then "Browse" and browse to the folder your cmdmp3 files are in and hit "OK".
4. Open a new powershell or cmd (whatever you're using) and re-run the test notification command and it should work :)

**Comment by rafaelffs** [comment]
Download mplayer binary and copy into your project folder:
http://www.mplayerhq.hu/design7/news.html
Should work fine

**Comment by pumpingdad** [comment]
Thanks @soalireofastora20 and @rafaelffs fixed it with cmdmp3 but used a differen link, this one: http://www.mailsend-online.com/wp/cmdmp3new.zip 
Streetmerchant still says "Couldnt find Sound Player" but actually plays the sound :-)
