### ISSUE TITLE
Otto wrong product

### ISSUE THREAD

**Issue by TDCroPower** [jef/streetmerchant#1163]
### Description

the wrong product is being tested at Otto.
You get the remote control instead of the consoles reported.

![otto_falsealert](https://user-images.githubusercontent.com/6634116/101200247-54129480-3666-11eb-9c5e-27f8df71b518.png)

### Possible solution

change Product ID ?

**Comment by TDCroPower** [comment]
oh ok, if I follow the links manually, Otto redirects me to the remote control.

German:
"Deinen gewünschten Artikel können wir leider nicht mehr liefern.
Hier findest du einen Artikel, der dir auch gefallen könnte."

English:
"Unfortunately, we can no longer deliver your desired article.
Here you will find an article that you might like."

![otto_umleitung](https://user-images.githubusercontent.com/6634116/101200607-d0a57300-3666-11eb-9a0b-2c6f47c9eee7.png)

Is there a way to prevent this?

**Comment by gigi2006** [comment]
its the same problem [here](https://github.com/jef/streetmerchant/issues/1132)

**Comment by TDCroPower** [comment]
Yes can anyone link the 2 bug reports?

**Comment by joerg-knitter** [comment]
I think the link _might_ be correct, because with the 3rd order wave on november 19th, I got a PS5 into my basket, but one day later, the order got cancelled. But in my order history, there is a link to the product page, and this is the same as in the otto.ts file.

One the other hand, I definately got no alarm by the script when I let it run yesterday with the default settings - which is kind of strange when they really sold a few consoles yesterday as reported in the media.
However, there are rumours out there that the orders were taken by phone and that they had only a small amount, so maybe they really did not sell anything online.

**Comment by jef** [comment]
> I think the link might be correct

I think you're right, because https://www.otto.de/p/playstation-5-1136008456/#variationId=1136008459 forwards to https://www.otto.de/p/playstation-5-medienfernbedienung-1170617135/#variationId=1170617136.

As of now, there isn't any way around this, except maybe `IN_STOCK_WAIT_TIME`, but that's not even a good solution.

Like @gigi2006 said, take a look at https://github.com/jef/streetmerchant/issues/1132#issuecomment-738120549. I believe that'll be the solution. I can see if I can do something about that.

I'll need help from contributors though to get the proper text. But I can code the implementation.

**Comment by jef** [comment]
I think adding something like this would be good

```diff
inStock: [
	{
		container:
			'button.prd_ordering__button.p_btn150--1st.js_product_addToBasket',
		text: ['In den Warenkorb']
+	},
+	{
+		container: '.js_shortInfo__variationName.prd_shortInfo__variationName',
+		text: ['konsole']
+	}
],
```

**Comment by jef** [comment]
Take a look at that PR and let me know if that looks good (in terms of what the text should say).
