### ISSUE TITLE
BestBuy-CA detecting 3060ti stock when it errors 403

### ISSUE THREAD

**Issue by rchenzheng** [jef/streetmerchant#1513]
## Expected Behavior

Should not alert in-stock when there is no stock but return the 403

## Current Behavior

Detects in-stock but it's actually an error including the screenshot

## Steps to Reproduce

https://www.bestbuy.ca/en-ca/product/zotac-geforce-rtx-3060-ti-twin-edge-8gb-gddr6-video-card

Run container

## Environment

**OS:** 
Docker
**dotenv file:**

```dotenv
MAX_PRICE_SERIES_3060TI=680
stores=bestbuy-ca

```

## Logs

```
[12:51:22 AM] info :: 🚀🚨 [bestbuy-ca] [zotac (3060ti)] twin edge :: IN STOCK 🚨🚀
https://www.bestbuy.ca/en-ca/product/zotac-geforce-rtx-3060-ti-twin-edge-8gb-gddr6-video-card/15178583?intl=nosplash
```

## Screenshot
https://ibb.co/4ds1Znq

**Comment by neatchee** [comment]
Well, that link was showing me what was in that screen-shot but now returns a proper 404 so I think this is fixed.
What leads you to believe that's 403? That might look more like a 404 or 410?

Either way it looks like the issue is that the page it lands on is returning a success status code, and the: ```async function lookupCardInStock(store: Store, page: Page, link: Link)``` falls through to true.

Anyway it should be fine for now?
