### ISSUE TITLE
Memoryexpress store in stock issue

### ISSUE THREAD

**Issue by Speedmod88** [jef/streetmerchant#1589]
## Expected Behavior

so I added rx5700xt video card and if I go manually in this store, there 2x remain card in stock at Calgary store
https://www.memoryexpress.com/Products/MX79287

## Current Behavior

I don't know why but the bot see it like OUT OF STOCK instead of IN STOCK 

## Steps to Reproduce

in src/store/model/memoryexpress.ts

add -> 	
	{
			brand: 'asus',
			model: 'strix',
			series: 'rx5700xt',
			url: 'https://www.memoryexpress.com/Products/MX79287'
		},

in src/store/model/store.ts

add in Serie -> 
	| 'rx5700xt'

in src/config.ts

add at line 203 -> rx5700xt: envOrArray(process.env.DISCORD_NOTIFY_GROUP_RX5700XT),

add at line 356 -> rx5700xt: envOrNumber(process.env.MAX_PRICE_SERIES_RX5700XT),

add at line 386 -> 'rx5700xt',

**Comment by anthonytam** [comment]
Currently the application is only monitoring the online stock of the products, not instore stock (With the exception of Microcenter I think)

By changing the CSS selector in src/store/model/memoryexpress.ts to the following string, you may be able to check instore stock (This string would be for Calgary specifically, however it could be adjusted for other stores as well)
```.c-capr-inventory-dropdown` > ul:nth-child(2) > li:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > li:nth-child(3) > div:nth-child(1) > span:nth-child(2)```

**Comment by Speedmod88** [comment]
I think in memoryexpress, depend on the region, everything is online and instore stock, I don't know how this work for this website but online, it write it clearly that is in stock for order but the bot don't see it

**Comment by anthonytam** [comment]
When an item is in stock at a specific store in Memoryexpress, you need to travel to that specific store to pickup the item, shipping is only available on items marked as in stock for the Online Store. For this reason, streetmerchant doesn't check the stock of the individual stores.

In order to check the stock for the stores, you would need to modify the memoryexpress.ts file as well as other components in the app to navigate the website menus to view store stock. This isnt a supported feature as of right now. If there is enough demand for the feature however, I'm sure it can be written up
