### ISSUE TITLE
recent lot of 503 errors

### ISSUE THREAD

**Issue by baD714** [jef/streetmerchant#1620]
## Expected Behavior

shoudl ping amazon

## Current Behavior

amazon throw 503 error after like 20 mins of runnign

**Comment by wofnull** [comment]
503 means that the server ( amazon ) is throtteling your connection, most likely you are requesting to often from amazon over period x of time. possible solutions to this is to raise the timeouts or use proxy(s)  ...

However since you did not provide a dotenv file with your error report, we can most likely not help you there.
