### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by mattar33** [jef/streetmerchant#1634]
## Expected Behavior

npm install

## Current Behavior

up to date, audited 1503 packages in 2s

7 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/axios
  axios-error  >=1.0.0-beta.16
  Depends on vulnerable versions of axios
  node_modules/axios-error
    messaging-api-telegram  *
    Depends on vulnerable versions of axios
    Depends on vulnerable versions of axios-error
    Depends on vulnerable versions of messaging-api-common
    node_modules/messaging-api-telegram
  messaging-api-common  >=1.0.0-beta.1
  Depends on vulnerable versions of axios
  node_modules/messaging-api-common
  node-hue-api  2.0.0-RC1 - 5.0.0-alpha.2
  Depends on vulnerable versions of axios
  node_modules/node-hue-api

5 high severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

## Environment

- OS:

windows
```

## Logs

<!-- Provide a brief log -->

**Comment by wofnull** [comment]
this message is normal and can be ignored ... you should be able to "npm run start" right after this.

The messages during npm install come up due to the fact that the project needs several dependencies from nodejs to run, and these are fix set in the configs of the project, jef updates them from time to time, so the messages about this come and go away or change up ... however they are save to ignore.
