### ISSUE TITLE
looks like EVGA and ASUS brands DO NOT work with bandh store. If i add MSI is starts working just fine. Possible something changed in their links?

### ISSUE THREAD

**Issue by lokixx** [jef/streetmerchant#1663]
## Expected Behavior

Store B&H not working with EVGA and ASUS brands. Works fine with MSI (haven't tested others)
## Current Behavior
Never checks for stock 

## Steps to Reproduce
Use my dotenv below and try 🤷 

## Environment

- OS:
- Unbuntu 18.04.4

```$
INCOGNITO=false
BROWSER_TRUSTED=true
HEADLESS=true
AUTO_ADD_TO_CART=true
#PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
COUNTRY=usa
DISCORD_NOTIFY_GROUP=<@&roleidhere>
DISCORD_WEB_HOOK=webhookhere
EMAIL_PASSWORD=passwordhere
EMAIL_TO=
EMAIL_USERNAME=email@email.com
LOG_LEVEL=info
MAX_PRICE_SERIES_3080=1300
OPEN_BROWSER=false
PHONE_CARRIER=verizon
PHONE_NUMBER=phonehere
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
SHOW_ONLY_BRANDS=evga,asus,msi
SHOW_ONLY_SERIES=3080
STORES="amazon,bestbuy,newegg,asus,adorama,bandh"
WEB_PORT=porthere
IN_STOCK_WAIT_TIME=30
LOW_BANDWIDTH=false
PAGE_BACKOFF_MIN=10000
PAGE_BACKOFF_MAX=3600000
PAGE_SLEEP_MIN=10000
PAGE_SLEEP_MAX=15000
PAGE_TIMEOUT=0
NVIDIA_ADD_TO_CART_ATTEMPTS=10
NVIDIA_SESSION_TTL=60000
SCREENSHOT=false


```

**Comment by wofnull** [comment]
could you please fill out the form?

we need aswell insight in your dotenv config to help or find the issue

**Comment by lokixx** [comment]
updated.

**Comment by wofnull** [comment]
Checked the Config for BandH:

As far as i can see there are 2 ASUS TUF Cards in the config "disabled" because they were removed in the past, one is now back in the store ( but out of stock ). Additional i found several additional Asus Cards on bandh.

Checking for EVGA, there is no EVGA card listed in the config at all. Looking in the 3080 / 3090 / 3070 / 3060ti Stocks of the store: They seem not to have a Single Card from EVGA listed in store at all. 

Therefore i will go ahead and open a pull request with the reenabled card which is currently "just" out of stock and the additional cards they have currently listed from asus. 

As i found out right now it seems that the inStock Check is somehow broken and i will put an fix in this aswell.

**Comment by wofnull** [comment]
Patch should be added shortly by jef

**Comment by lokixx** [comment]
was the problem found?

**Comment by wofnull** [comment]
yeah i found the problem and provided a patch yesterday , waiting to be merged into the main repo by @jef

**Comment by lokixx** [comment]
so it looks like this fixed Asus with BandH, but EVGA 3080s still arnt being listed
