### ISSUE TITLE
EVGA not fixed with BandH. Doesn't Search. BandH seems to only search MSI (Various models) and ASUS (only the TUF model)

### ISSUE THREAD

**Issue by lokixx** [jef/streetmerchant#1694]
## Expected Behavior
EVGA should be searchable via BandH

## Current Behavior
EVGA is not searchable via BandH.

## Steps to Reproduce
Run with my confis

## Environment

- OS: Unbuntu 

```INCOGNITO=false
BROWSER_TRUSTED=true
HEADLESS=true
AUTO_ADD_TO_CART=true
#PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
COUNTRY=usa
DISCORD_NOTIFY_GROUP=<@&roleidhere>
DISCORD_WEB_HOOK=webhookhere
EMAIL_PASSWORD=passwordhere
EMAIL_TO=
EMAIL_USERNAME=email@email.com
LOG_LEVEL=info
MAX_PRICE_SERIES_3080=1300
OPEN_BROWSER=false
PHONE_CARRIER=verizon
PHONE_NUMBER=phonehere
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
SHOW_ONLY_BRANDS=evga,asus,msi
SHOW_ONLY_SERIES=3080
STORES="amazon,bestbuy,newegg,asus,adorama,bandh"
WEB_PORT=porthere
IN_STOCK_WAIT_TIME=30
LOW_BANDWIDTH=false
PAGE_BACKOFF_MIN=10000
PAGE_BACKOFF_MAX=3600000
PAGE_SLEEP_MIN=10000
PAGE_SLEEP_MAX=15000
PAGE_TIMEOUT=0
NVIDIA_ADD_TO_CART_ATTEMPTS=10
NVIDIA_SESSION_TTL=60000
SCREENSHOT=false
```

**Comment by wofnull** [comment]
As said before in #1663 : 
Checking for EVGA, there is no EVGA card listed in the config at all. **Looking in the 3080 / 3090 / 3070 / 3060ti Stocks of the store: They seem not to have a Single Card from EVGA listed in store at all.**

They do not have any card from EVGA in the 30 series, so i do not have any link to any card for streetmerchant to lookout for. So the bot is not able to give you prices for them. Simply as that: Streetmerchant will not work for 30 series EVGA cards on B&H, because B&H does not have any 30 series EVGA Card at all listed!

See for yourself:
https://www.bhphotovideo.com/c/products/Graphic-Cards/ci/6567/N/3668461602?filters=fct_brand_name%3Aevga

No 30 series EVGA Cards, only 20 and 10 Series cards.

**Comment by jef** [comment]
Going to close this out based on @wofnull's response. Thank you for your help ☺️
