### ISSUE TITLE
Best Buy pages stuck loading indefinitely with a proxy configured as of v3.4.1 and v3.4.0 (works fine in v3.3.0)

### ISSUE THREAD

**Issue by HawkyYT** [jef/streetmerchant#1766]
Best Buy pages are not loading with a proxy in 3.4.1 or 3.4.0. Page will stay stuck loading on a white screen until `PAGE_TIMEOUT` is reached or indefinitely if you have no timeout. Other sites (amazon, newegg) are loading just fine with the same proxy settings whether in `global.proxies` or separately.

If I set my proxy in my Windows settings (with no proxy configured in streetmerchant) Best Buy sites load fine both in streetmerchant and in a standalone browser like Chrome, so I know Best Buy has not blocked my proxy server.

I have tried all combinations of http, socks5, username/pass credentials enabled and disabled within `global.proxies` and `bestbuy.proxies`

This issue is not present in release v3.3.0. Best Buy pages load fine on that release with identical proxy and `dotenv`.

## Steps to Reproduce

Set streetmerchant to run headful `HEADLESS=false`. Configure for bestbuy store and listings. Also configure another store such as amazon or newegg to compare. Set `PAGE_TIMEOUT` to `0`. Configure proxy in `bestbuy.proxies` file. NOTE: `global.proxies` does not appear to work in v3.3.0, each store must have a separate proxies file.

Run streetmerchant on latest release v3.4.1. Notice that the tab for Best Buy never loads but also never errors. If you set a timeout or the default 30 seconds it will always timeout.

Switch to release v3.3.0: `git checkout b97d581` and `npm install`.

Run streetmerchant release v3.3.0. The Best Buy tab will load correctly and the command line will report its stock.

## Environment

- OS: Windows 10 x64 20H2
- streetmerchant: v3.4.1, v3.4.0

```# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
COUNTRY=
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
HEADLESS=false
IN_STOCK_WAIT_TIME=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
NVIDIA_ADD_TO_CART_ATTEMPTS=
NVIDIA_SESSION_TTL=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=0
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_RETRY=
PUSHOVER_TOKEN=
PUSHOVER_USER=
PUSHOVER_PRIORITY=
SCREENSHOT=
SHOW_ONLY_BRANDS=amd
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=bestbuy,amazon,newegg
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
WEB_PORT=
```

**Comment by HawkyYT** [comment]
**Update**: Proxy works with Best Buy in release v3.4.1 if you enter your proxy info in `dotenv` and have no `global.proxies` or `bestbuy.proxies` files present. This of course means you can only use one proxy though, which defeats the purpose really. What this does do though is prove that there is an issue with how proxies are used in the `.proxies` files in relation to Best Buy.

I'm able to confirm that streetmerchant is using the proxy info in `dotenv` by changing one of the product URLs in the `bestbuy.ts` file to `https://whatismyipaddress.com/` and running `HEADLESS=false`. It's stupid, but it works. Chromium opens and the website loads and correctly reports my proxy IP. Switch the product URL back to the actual product and it connects no problem.

**Comment by HuandongGuo** [comment]
everything runs fine except the best buy, somebody help me with the proxy stuff, I don't see any useful file except the dotenv

**Comment by PacketShepard** [comment]
I'm having this same problem. BestBuy breaks with global.proxies and I have to disable proxies for it by creating a blank bestbuy.proxies file. It doesn't appear to be blocked by my proxies.

**Comment by Fmstrat** [comment]
I also have this problem with Best Buy. As it is also related to using rotating proxies, it could be related to the `net::ERR_FAILED` issue, too: https://github.com/jef/streetmerchant/issues/1844

**Comment by Fmstrat** [comment]
Anti-botting since it's still happening.

**Comment by d1zzy** [comment]
I have this issue too, on both bestbuy and amd (but works fine for "amazon", haven't tried newegg). It only happens if using *.proxies file (and it happens with a single entry too, not required to have multiple entries to the file). If I put the same proxy in the dotenv file and empty the *.proxies files then it works fine for both bestbuy and amd so clearly it's not a proxy ban issue. I reproduced this issue both in nightly and latest stable (3.5.0). Please help!

**Comment by PacketShepard** [comment]
> I have this issue too, on both bestbuy and amd (but works fine for "amazon", haven't tried newegg). It only happens if using *.proxies file (and it happens with a single entry too, not required to have multiple entries to the file). If I put the same proxy in the dotenv file and empty the *.proxies files then it works fine for both bestbuy and amd so clearly it's not a proxy ban issue. I reproduced this issue both in nightly and latest stable (3.5.0). Please help!

Still having the same issue here as well and I know my proxy can reach Best Buy with no problem. I've disabled Best Buy due to this issue for now.

**Comment by d1zzy** [comment]
I did a bunch of additional tests tonight, nothing fixed this issue:
1. I tried 3.4.1 and 3.3.0 versions
2. I tried downgrading the Node.JS (from 15.x to latest 14.x LTS)
3. Installed an HTTP proxy (instead of a SOCKS5 proxy I was trying earlier) and confirmed that the same happens with HTTP proxies in *.proxies files too (for amd/bestbuy)
4. I tried newegg store and that one seems to be working fine, just like amazon, only amd/bestbuy are affected by this issue
5. I captured the traffic on the proxy host to see what is going on and things looked fine at a glance: the SOCKS5 connection is established, a SOCKS5 handshake does take place and a connection to the BestBuy web server is requests (by IP address), then I saw proxied traffic which looked like TLS handshake (saw some SSL certificates for api.bestbuy.com) then followed by some encrypted traffic but after that nothing happening
6. Even tried disabling IPV6 on my Windows host (where I attempt to run streetmerchant to connect to Linux SOCKS5/HTTP proxies) thinking that maybe something is broken in regards to IPV6, but that also didn't help.

Again, when I put the same proxy in the dotenv file or manually in my browser, everything seems to work fine so it's not a proxy IP ban. It just doesn't work for amd/bestbuy stores when I put any proxy I tried in the *.proxies files. 

Can someone else confirm that for them it works to add a SOCKS5/HTTP proxy to amd.proxies/bestbuy.proxies/global.proxies file and then the store pages for amd/bestbuy load just fine through that proxy?
