### ISSUE TITLE
Scan UK linkbuilder not working

### ISSUE THREAD

**Issue by GeneralPeake** [jef/streetmerchant#2626]
## Expected Behavior

Program should be able to build links to products on Scan UK

## Current Behavior

It tries continuously but never manages to build links

## Steps to Reproduce

Only Code changes below 

AUTO_ADD_TO_CART=true
BROWSER_TRUSTED=false
COUNTRY=great_britain
HEADLESS=true
IN_STOCK_WAIT_TIME=0
LOG_LEVEL=info
LOW_BANDWIDTH=false
PAGE_SLEEP_MIN="30000"
SHOW_ONLY_SERIES=3080,3070
STORES=scan

![image](https://user-images.githubusercontent.com/86048685/122374195-11593f80-cf5a-11eb-93cd-fcf9134e6071.png)

## Environment

- OS: Windows 10

**Comment by daningamells** [comment]
Hey @GeneralPeake ,

Have you attempted this with "headless=false"?

You will see the reason this never builds links is because the page never actually gets passed the Cloudfare protection.

You will see the Ray ID keep changing and you will be stuck in a loop until the page eventually closes.

I have spent hours looking at this but have no solution.

Please help!!!!!!

**Comment by GeneralPeake** [comment]
Hi @daningamells ,

I tried updating the code and seems I was behind the latest version. Sorry for not realizing that the code had not been updated. I no longer get the infinite linksbuilder message and instead get a warning stating "some of the selected stores (grayed out) don't have what you are looking for" as per the image below. Any idea what might be causing this?

![image](https://user-images.githubusercontent.com/86048685/122785056-f1ec4a80-d2aa-11eb-9308-2e97cc74cde6.png)

Regards,
Kieran.
