### ISSUE TITLE
Possible to add function for two phon numbers?

### ISSUE THREAD

**Issue by jordanhgaytan** [jef/streetmerchant#273]
Have two phones, one personal and one work phone. Would be awesome to have both be able to receive a notification!

Is this remotely possible?

**Comment by jordanhgaytan** [comment]
spelling

**Comment by geman220** [comment]
It's possible but it's going to be an extremely low priority in comparison to other enhancements unless someone wants to fork and add it.

**Comment by adolfox** [comment]
@jef Is this still something you want to implement?  I was thinking of taking a crack at it.

**Comment by adolfox** [comment]
I'm doing Hacktoberfest.  I need two more PRs :)

**Comment by jef** [comment]
> I'm doing Hacktoberfest. I need two more PRs :)

Go for it! I don't mind having this in here. Makes sense to me.

**Comment by adolfox** [comment]
So I was thinking that in order to keep the .env compatibility intact that I'd just extend on the current variables in the .env.  I was thinking that people that want multiple numbers, would just comma separate the list of number and then in the corresponding order, comma separate the carriers, something like:

PHONE_NUMBER="5121234567, 9876543987"
PHONE_CARRIER="tmobile,att"

Does that work for you?

**Comment by jef** [comment]
Yep, I think that's great. No spaces between `,` (probably a typo), but that looks great. Perhaps we can also `trim()` these environment variables in the `envOr*()` functions.

**Comment by adolfox** [comment]
Yeap, the space was a mistake.  Sounds good.  I'll get started on it.  And yeah, I'll trim() in case anyone includes spaces like I just did.
