### ISSUE TITLE
[Bug]: Amazon-it is ignoring MAX_PRICE_SERIES filter

### ISSUE THREAD

**Issue by Bruner4** [jef/streetmerchant#2889]
### Expected Behavior

Streetmerchant should have ignored the amazon-it items that were coming back with higher price tags than what was specified in the MAX_PRICE_SERIES filter.

### Current Behavior

Streetmerchant is instead accepting amazon-it items that have a higher price tag than what is specified in the MAX_PRICE_SERIES filter
![amazon1](https://user-images.githubusercontent.com/32824898/146992321-00325f10-0834-4ad0-b422-513f029a4f3e.jpg)
![amazon2](https://user-images.githubusercontent.com/32824898/146992325-c64eb9fd-2d52-43c6-9d4d-0c6a52891da7.jpg)
.

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
[21:10:43] info :: 🚀🚨 [amazon-it] [asus (3080)] tuf :: IN STOCK 🚨🚀
https://www.amazon.it/gp/aws/cart/add.html?ASIN.1=B08HHDP9DW&Quantity.1=1
```

### Configuration

```shell
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.buzz/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
CAPTCHA_HANDLER_CAPTURE_TYPE=
CAPTCHA_HANDLER_POLL_INTERVAL=
CAPTCHA_HANDLER_RESPONSE_TIMEOUT=
CAPTCHA_HANDLER_SERVICE=
CAPTCHA_HANDLER_TOKEN=
CAPTCHA_HANDLER_USER_ID=
DESKTOP_NOTIFICATIONS="true"
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3070TI=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3080TI=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
GOTIFY_PRIORITY=
GOTIFY_TOKEN=
GOTIFY_URL=
HEADLESS=
IN_STOCK_WAIT_TIME=
INCOGNITO=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3070TI=
MAX_PRICE_SERIES_3080="1100"
MAX_PRICE_SERIES_3080TI="1100"
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
OPEN_BROWSER=
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_DEVICE=
PUSHOVER_PRIORITY=
PUSHOVER_RETRY=
PUSHOVER_SOUND=
PUSHOVER_TOKEN=
PUSHOVER_USER=
RESTART_TIME=
SCREENSHOT=
SCREENSHOT_DIR=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES="sonyps5c,3080,3080ti"
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES="amazon-it,amazon-de,comet,euronics,unieuro,amazon-fr,playstation,amd,amd-it,asus,bestbuy,evga-eu,nvidia,zotac"
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
STREAMLABS_DURATION=
FREEMOBILE_ID=
FREEMOBILE_API_KEY=
WEB_PORT=
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tormarod** [comment]
Same thing happening to me for amazon-es

**Comment by AndroidDev77** [comment]
This problem is addressed on fix(amazon-eu): checking price selector #2856

**Comment by dlisi** [comment]
@jef Goodmorning everybody, I also noticed the same issue, inspected dom elements and found that the element showing price is called:

a-price-whole

changing store.ts to inspect that tag seems to make the software works, but please don't get my words for granted since my actual knowledge of this software is very limited at the moment. Maybe someone with more grasp on it, can confirm or deny my assumption

**Comment by schroedaa** [comment]
@dlisi Can you show which point exactly in the Store.ts needs to be changed? Thanks a lot

**Comment by dlisi** [comment]
Good morning,
first of all sorry, but I wrote store.ts but what I meant was "name of the store".ts

***@***.***

The line circled in red is the one that works with the tag I suggested in my comment, the small caveat is that it does scrape only the integer part of the price, but it seems like a good compromise.
I think also the span with class name "a-offscreen" can be used since it contains the whole price plus currency, but I didn't test that
Have a good day,

Diego Lisi

FSTechnology S.p.A.
Sourcing Plan, Sustainability & Risk
Rapid Solution Prototyping

cell. 331 616 7962
Via Salandra 13, 00187 ROMA

[signature_774329221]Seguici su LinkedIn<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffstechnology-spa%2F&data=04%7C01%7C%7C207555b4a2f3410c2dc408d9a0648184%7C4c8a6547459a4b75a3dcf66efe3e9c4e%7C0%7C0%7C637717175786226945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x%2BAc8M0xxaxyGHKyk3c4bfdvEC6RWcBGHGXK8nG00Ms%3D&reserved=0>

Rispetta l'ambiente: se non è necessario, non stampare questa mail

Da: schroedaa ***@***.***>
Inviato: domenica 6 marzo 2022 12:15
A: jef/streetmerchant ***@***.***>
Cc: LISI DIEGO ***@***.***>; Mention ***@***.***>
Oggetto: Re: [jef/streetmerchant] [Bug]: Amazon-it is ignoring MAX_PRICE_SERIES filter (Issue #2889)


@dlisi<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlisi&data=04%7C01%7C%7C884a1fc393e741631cce08d9ff629220%7C4c8a6547459a4b75a3dcf66efe3e9c4e%7C0%7C0%7C637821621692275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FVajGgXX9EDRLZXVA6EDjrbRF%2F2INkmMc9o35qFkVHE%3D&reserved=0> Can you show which point exactly in the Store.ts needs to be changed? Thanks a lot

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjef%2Fstreetmerchant%2Fissues%2F2889%23issuecomment-1059942733&data=04%7C01%7C%7C884a1fc393e741631cce08d9ff629220%7C4c8a6547459a4b75a3dcf66efe3e9c4e%7C0%7C0%7C637821621692275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Zj2L%2BpMK5iBNIw%2B91GiYJo1uM8Cxs1j0Ns4yow8LmDQ%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXPUNUXOIF3SPONA4PBO4KTU6SHTNANCNFSM5KQ75SBA&data=04%7C01%7C%7C884a1fc393e741631cce08d9ff629220%7C4c8a6547459a4b75a3dcf66efe3e9c4e%7C0%7C0%7C637821621692275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iLMwzU2tVFieTzhiZm0IVIWdmOnWR6sz7ifOsy6wcbE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C884a1fc393e741631cce08d9ff629220%7C4c8a6547459a4b75a3dcf66efe3e9c4e%7C0%7C0%7C637821621692275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=frmycSJQV%2Bckxotp%2FVzLMBIzSd8S2xDUzAXfP6jcDK0%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C884a1fc393e741631cce08d9ff629220%7C4c8a6547459a4b75a3dcf66efe3e9c4e%7C0%7C0%7C637821621692275239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8Iezdt9ucfMY106Pm4upoQOseWrED5Pfr3kSEvtc5NA%3D&reserved=0>.
