### ISSUE TITLE
Error 503 for Zotac's site

### ISSUE THREAD

**Issue by daddysspecialboy** [jef/streetmerchant#326]
Zotac was working yesterday, but now while running nvidia-snatcher every time a 3080 is checked at Zotac it comes back as Error 503. I have all of the American stores in my .env and all the rest work fine. 

It's been that way for a few hours now. Since last night, every time I go to Zotac's site manually I hit an anti-DDOS page that requires a captcha. Possibly related?

**Comment by andrewmackrodt** [comment]
Yes it sounds like it's related to the anti-ddos/bot behaviour. There was a change recently in snatcher to return more detailed messages when stock status could not be checked; previously it would return "out of stock" although it may not have been able to check the stock status so that's a false negative.

Typically 500-504 errors are due to the service being unavailable, e.g. there aren't enough servers to handle the demand. It seems Zotac use a 503 for their captcha page. Would you be able to capture a [HAR file](https://confluence.atlassian.com/kb/generating-har-files-and-analyzing-web-requests-720420612.html#GeneratingHARfilesandanalyzingwebrequests-Solution) using an incognito window for Zotac's captcha page so we can add a captcha check for that store? Alternatively, it will be enough to just save the page source.

**Comment by matjam** [comment]
they're using cloudflare now, so we'd need to know the original IP of the zotec store, right? I've tried to dig around but can't find anything right now.

**Comment by MattTheTechLV** [comment]
I just now saw this error, or I might have posted in here instead, but I just submitted a feature enchancement request that should fix this issue for now (Until Zotac gets a little bit smarter with their captcha system), see issue #343 for how I defeated it. It seems to be reliable, have been running this way for a little over 2 hours now, and it seems to do the trick. However, FYI, I run My Instances all behind a VPN that Automatically switches IP's every 30 minutes as to not get IP Blocked. So If using this fix for multiple hours at a time, without changing IPs, I do not know if it will be as reliable.

**Comment by danmaxis** [comment]
@MattTheTechLV how did you attach your instances to a vpn?

**Comment by sfatz** [comment]
It looks like this issue is back. I'm seeing the 503 error on Zotac's site again.  Looked through Issue #343, but it appears that the lookup.ts code has changed enough that it doesn't really work the same way as when MattTheTechLV worked around it.  Any ideas on a new workaround?

**Comment by SebastianKurpSyn** [comment]
Any update on this?
