### ISSUE TITLE
PS5 walmart + Gamestop + playstation not able to be scraped.

### ISSUE THREAD

**Issue by gamre20** [jef/streetmerchant#851]
There is no alert nor any detection for Walmart, GameStop, PlayStation on the recent release of the PS5. Didn't any log/error but it just couldn't scrape it even though I had the script running thanks!

**Comment by DamnNewbie** [comment]
I posted this to discord, but adding it to this bug.
"The playstation stuff seems to be bugged and always showing "outofstock" at least for Walmart and direct.playstation.com.  I just spent time sitting in the queue (playstation direct 4pm ET today) and hitting the rest api it comes back as in stock, but the application keeps reporting out of stock the entire time.  Did they same during walmart 3pmET launch today, but I did not have the manually api queries to back it up."

I was hitting the direct.playstation.com API manually while i was in the queue today (randomly checking after application didn't work for Walmart today).  Hey at least Sony told you they were gone today.  Within a couple of minutes of the api reporting outofstock the queue-it system posted a message they were gone so that you could get out of queue if you wanted.

api for digital edition:  https://api.direct.playstation.com/commercewebservices/ps-direct-us/products/productList?fields=BASIC&productCodes=3005817

**Comment by J-Hinton** [comment]
I believe the issue could be caused by the queueing system they are using. It might be struggling to scrap because it gets redirected to this holding page. Maybe we need to think about a PlayStation API store for real-time data which would bypass this potential issue.

**Comment by DamnNewbie** [comment]
Yeah, even if it would only notify when in stock using email/sms it would help.  Then you could quickly get in queue and maybe get lucky.  I didn't realize that with "realTimeInventoryLookup" it was still trying to scrap afterwards, but learning that makes more sense why it wasn't working.

For Walmart (no api at this time in the app), the site is getting absolutely blasted and the scraping is likely failing.  You'd have to be trying once a second and hope your request made it through.  I again had ps5 in my cart today on walmart and was trying to pay only to have it say out of stock.  I got dozen of error pages just getting to that point.
