### ISSUE TITLE
Problem with .env looking for consoles

### ISSUE THREAD

**Issue by louij2** [jef/streetmerchant#867]
### Description

![image](https://user-images.githubusercontent.com/2940588/99850434-4395f080-2b75-11eb-843f-68c02691aaf9.png)
I have selected only consoles but when I npm run start it shows all options

**Comment by Lukalion** [comment]
You need to put your options into SHOW_ONLY_SERIES instead of SHOW_ONLY_MODELS.  models is for sorting board partners

**Comment by louij2** [comment]
> 
> 
> You need to put your options into SHOW_ONLY_SERIES instead of SHOW_ONLY_MODELS. models is for sorting board partners

This helped the initial output but for some reason I still can't see the xbox logs but I can see the PS5 ones on all sites the same way? 
![image](https://user-images.githubusercontent.com/2940588/99856902-f2d8c480-2b81-11eb-94f6-8ce551462eba.png)

**Comment by Lukalion** [comment]
hmm. two things that might fix it. 1st check if you have stores included in your list that have xbox listed in them. because amazon doesnt have the same links as amazon-uk and so on. I for example had to add 6800/6800xt and 6900xt to the amd-de site manually to get that working. the same may apply here too with amazon. do a test if you can see the xbox if you add all stores. if you can see them, then you probably have to add the xbox direct links manually to your shops. They are located in /streetmerchants/src/store/model/ with the shops ending in .ts. 2 thing check the written links in .ts if they are correct and working.

**Comment by louij2** [comment]
Yes I added the xbox to Amazon-UK as you can see on the left. I tried removing the incorrect add to cart links too but alas nothing

**Comment by jef** [comment]
Just use `SHOW_ONLY_SERIES`. No need to use models. That's for more generic usage on other products.
