### ISSUE TITLE
Why do you need my email password, seems like a scam?

### ISSUE THREAD

**Issue by Niswendel** [jef/streetmerchant#993]

**Comment by MujiSayed** [comment]
to send u an email notification/sms text. if ur using gmail, u can use an app password instead.

**Comment by MRizkBV** [comment]
Imagine calling this a scam.

Let me explain what it is needed for:
1. It is not required, it is optional. You only have to enter it if you want to receive email notifications (or texts/SMS on the supported carriers)
2. Such info is required because this is an open source project and they are not going to integrate it with a paid emailing service and pay out of pocket

Honestly, you should just avoid it anyways. Emails are slow for such high demand items. Use Discord/Telegram/Pushover and sound notifications.

**Comment by controledxchaos** [comment]
I created an email just for this. to avoid giving my own password out for personal account.

**Comment by peacepenguin** [comment]
You're giving your email address and password to your own code running on your own system. No ones collecting that data, you're just entering it so you can send yourself an email.

**Comment by thefl0yd** [comment]
If you don't understand what the program is maybe you shouldn't be using it. At the last poster noted, you're putting your email password in a configuration file for a program running on your machine.

**Comment by jiglesiasc** [comment]
This software is 100% legit and safe. The software need the password to be able to "log.in" in to the email your account so it can send an email notification.
