### ISSUE TITLE
Running this script is like mining CPU hits high 90% to 100 I have an intel Gen 10 

### ISSUE THREAD

**Issue by ufomike** [jef/streetmerchant#994]
### High CPU clock 

When running this script my CPU is clocking at 90% plus. Is this normal or should I make any changes to get the CPU usage down?

**Comment by thefl0yd** [comment]
the program runs web browsers in the background that continually fetch web sites, scrape for information (like "in stock" or "add to cart") and make a decision based on that.

You're basically mining for a GPU (or ps5. or whatever you're looking for). So yes. high CPU usage is expected.

**Comment by jiglesiasc** [comment]
Check your power settings. My CPU is an 8th gen (8700k) and the script consumes from 20-30%, and your CPU should be stronger.

**Comment by j0um** [comment]
I also have a 8700k and I confirm the script will use all cpu resources. I'm scraping 10+ stores and all gpus.

**Comment by jiglesiasc** [comment]
I was scanning for only the 3080 in 3 stores at the lowest frequency possible. I'm not sure if scanning for that much video cards and that much stores is good, unless you run different instances of streetmerchant otherwise you'll be checking the same link each 5 minutes or more which is not going to work

**Comment by jef** [comment]
Try `LOW_BANDWIDTH=true`. Also for a laugh: [Mac Pro 1.5 TB RAM Upgrade vs Google Chrome](https://youtu.be/ldDTgp5irKA).
